// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfb11f9k7tjBjIalkeLcoMjyMruEwEjd4',
    appId: '1:77958225076:web:8d355187cf09d831b3cbe1',
    messagingSenderId: '77958225076',
    projectId: 'mehrantech46',
    authDomain: 'mehrantech46.firebaseapp.com',
    storageBucket: 'mehrantech46.appspot.com',
    measurementId: 'G-6J0EH7F8YH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ5zREQNlZJlwGbszvWiEbmZxssi25BPg',
    appId: '1:77958225076:android:52d41205f82018c1b3cbe1',
    messagingSenderId: '77958225076',
    projectId: 'mehrantech46',
    storageBucket: 'mehrantech46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmAtYvQEXaVpt3A_xvYrup12cg0mqfIy8',
    appId: '1:77958225076:ios:3d01712b3af19975b3cbe1',
    messagingSenderId: '77958225076',
    projectId: 'mehrantech46',
    storageBucket: 'mehrantech46.appspot.com',
    iosBundleId: 'com.example.mehrantech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmAtYvQEXaVpt3A_xvYrup12cg0mqfIy8',
    appId: '1:77958225076:ios:3d01712b3af19975b3cbe1',
    messagingSenderId: '77958225076',
    projectId: 'mehrantech46',
    storageBucket: 'mehrantech46.appspot.com',
    iosBundleId: 'com.example.mehrantech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfb11f9k7tjBjIalkeLcoMjyMruEwEjd4',
    appId: '1:77958225076:web:dd1e2dd7c26a82d2b3cbe1',
    messagingSenderId: '77958225076',
    projectId: 'mehrantech46',
    authDomain: 'mehrantech46.firebaseapp.com',
    storageBucket: 'mehrantech46.appspot.com',
    measurementId: 'G-1DX3MT9F3Q',
  );
}
